[package]
name = "transit-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
tch-backend = ["transit-training/tch-backend"]
tch-doc-only = ["tch-backend", "transit-training/tch-doc-only"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
transit-dataset = { path = "../transit-dataset" }
transit-domain = { path = "../transit-domain" }
gtfs-compile = { path = "../gtfs-compile" }
gtfs-ingest = { path = "../gtfs-ingest" }
gtfs-source = { path = "../gtfs-source" }
transit-graph = { path = "../transit-graph" }
transit-inference = { path = "../transit-inference" }
transit-labels = { path = "../transit-labels" }
transit-model = { path = "../transit-model" }
transit-router = { path = "../transit-router" }
transit-search = { path = "../transit-search" }
transit-training = { path = "../transit-training" }
