[package]
name = "transit-dataset"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
transit-domain = { path = "../transit-domain" }
transit-graph = { path = "../transit-graph" }
transit-labels = { path = "../transit-labels" }

[dev-dependencies]
gtfs-compile = { path = "../gtfs-compile" }
gtfs-ingest = { path = "../gtfs-ingest" }
tempfile.workspace = true
