[package]
name = "transit-model"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["reference-backend"]
reference-backend = []
tch-backend = ["dep:tch"]
tch-doc-only = ["tch-backend", "tch/doc-only"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
transit-domain = { path = "../transit-domain" }
transit-graph = { path = "../transit-graph" }
transit-labels = { path = "../transit-labels" }
tch = { version = "0.18", optional = true }

[dev-dependencies]
chrono.workspace = true
gtfs-compile = { path = "../gtfs-compile" }
gtfs-ingest = { path = "../gtfs-ingest" }
